/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_f103c6_Drivers_Gpio.h"
#include "Stm32f103x6.h"
#include "LCD.h"
#include "KEY_PAD.h"
void LCD_Send_String(char* string){//: writes a string of characters to the LCD display.

		int count = 0;
		while (*string > 0){// if became at end will be =0
			count++;
			LCD_Send_A_Character(*string++);
			if (count == 16)
			{
				LCD_GOTO_XY(2,0);
			}
			else if (count == 31)
			{
				LCD_clear_screen();
				LCD_GOTO_XY(1,0);
				count = 0;
			}
		}
	}
//#include "KEY_PAD.h"
void clock_Init(){
	//Enable clock IOPA EN
	RCC_GPIOA_CLK_EN();
	//Enable clock IOPB EN
	RCC_GPIOB_CLK_EN();

}
void GPIOA_INIT(){
	GPIO_PIN_CONFIG_T PinCfg;
	//Pin A1 is INPUT HighZ Floating Input
	PinCfg.GPIO_PinNumber=GPIO_PIN_1;
	PinCfg.GPIO_PinMode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA_PR, &PinCfg);
	//Pin B1 is OUTPUT
	//01: Output mode, max speed 10 MHz.
	PinCfg.GPIO_PinNumber=GPIO_PIN_1;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	//Pin A13 is INPUT HighZ
	//00: Input mode (reset state)
	//01: Floating input (reset state)
	PinCfg.GPIO_PinNumber=GPIO_PIN_13;
	PinCfg.GPIO_PinMode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA_PR, &PinCfg);

	//Pin B13 is OUTPUT
	//01: Output mode, max speed 10 MHz.
	PinCfg.GPIO_PinNumber=GPIO_PIN_13;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);


}
my_wait(int a){
	unsigned int i,j;
	for(i=0;i<a;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_Init();
	LCD_init();
	Keypad_init();

    unsigned char key_pressed;
	char Name[20]={"Mina Sabry"};
	LCD_Send_String(&Name);
	my_wait(500);
	LCD_clear_screen();

	while(1){
		key_pressed = Keypad_getkey();
	    switch(key_pressed){
		    case 'A':
		    break;
		    case '?':
		    LCD_clear_screen();
		    break;
		    default:
		    LCD_Send_A_Character(key_pressed);
		    break;

	}

}
}
