/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_f103c6_Drivers_Gpio.h"
#include "Stm32f103x6.h"
#include "LCD.h"
#include "KEY_PAD.h"

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10


void LCD_Send_String(char* string){//: writes a string of characters to the LCD display.

		int count = 0;
		while (*string > 0){// if became at end will be =0
			count++;
			LCD_Send_A_Character(*string++);
			if (count == 16)
			{
				LCD_GOTO_XY(2,0);
			}
			else if (count == 31)
			{
				LCD_clear_screen();
				LCD_GOTO_XY(1,0);
				count = 0;
			}
		}
	}
//#include "KEY_PAD.h"
void clock_Init(){
	//Enable clock IOPA EN
	RCC_GPIOA_CLK_EN();
	//Enable clock IOPB EN
	RCC_GPIOB_CLK_EN();

}
void GPIOB_INIT(){
	GPIO_PIN_CONFIG_T PinCfg;

	//Pin A9>>A15 Are OUTPUT
	// Output mode, max speed 10 MHz.
	PinCfg.GPIO_PinNumber=GPIO_PIN_9;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	PinCfg.GPIO_PinNumber=GPIO_PIN_10;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	PinCfg.GPIO_PinNumber=GPIO_PIN_11;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	PinCfg.GPIO_PinNumber=GPIO_PIN_12;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	PinCfg.GPIO_PinNumber=GPIO_PIN_13;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	PinCfg.GPIO_PinNumber=GPIO_PIN_14;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	PinCfg.GPIO_PinNumber=GPIO_PIN_15;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);



}
my_wait(int a){
	unsigned int i,j;
	for(i=0;i<a;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_Init();
	LCD_init();
    unsigned char key_pressed;
	char Name[20]={"Mina Sabry Hello:"};
	LCD_Send_String(&Name);
	my_wait(100);
	LCD_clear_screen();
	GPIOB_INIT();
	unsigned char SEG [] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	unsigned char LCD_DISPLAY [] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	for (unsigned char i = 0; i < 11; i++) {
			LCD_Send_A_Character(LCD_DISPLAY[i]);
			MCAL_GPIO_WritePort(GPIOB_PR, SEG[i] << 9); /* Shifted because the 7-Seg Began at port 9 */
			my_wait(100);
			/* wait for 1 second */
		}
	LCD_clear_screen();
	Keypad_init();
	LCD_Send_String("KEyPad is Ready!!!");
	my_wait(30);
	LCD_clear_screen();


	while(1){
		key_pressed = Keypad_getkey();
	    switch(key_pressed){
		    case 'A':
		    break;
		    case '?':
		    LCD_clear_screen();
		    break;
		    default:
		    LCD_Send_A_Character(key_pressed);
		    break;

	}

}
}
