/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "Stm32_f103c6_Drivers_Gpio.h"
#include "Stm32f103x6.h"

void clock_Init(){
	//Enable clock IOPA EN
	RCC_GPIOA_CLK_EN();
	//Enable clock IOPB EN
	RCC_GPIOB_CLK_EN();

}
void GPIOA_INIT(){
	GPIO_PIN_CONFIG_T PinCfg;
	//Pin A1 is INPUT HighZ Floating Input
	PinCfg.GPIO_PinNumber=GPIO_PIN_1;
	PinCfg.GPIO_PinMode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA_PR, &PinCfg);
	//Pin B1 is OUTPUT
	//01: Output mode, max speed 10 MHz.
	PinCfg.GPIO_PinNumber=GPIO_PIN_1;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);

	//Pin A13 is INPUT HighZ
	//00: Input mode (reset state)
	//01: Floating input (reset state)
	PinCfg.GPIO_PinNumber=GPIO_PIN_13																;
	PinCfg.GPIO_PinMode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA_PR, &PinCfg);

	//Pin B13 is OUTPUT
	//01: Output mode, max speed 10 MHz.
	PinCfg.GPIO_PinNumber=GPIO_PIN_13;
	PinCfg.GPIO_PinMode=GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB_PR, &PinCfg);


}
my_wait(int a){
	unsigned int i,j;
	for(i=0;i<a;i++)
		for(j=0;j<255;j++);


}

int main(void)
{
	clock_Init();
	GPIOA_INIT();

	while(1){
		//Read Bit 1  ..PA1>>Connected External to PUR
		if(MCAL_GPIO_ReadPin(GPIOA_PR, GPIO_PIN_1) ==0)//Press
		{
			MCAL_GPIO_TogglePin(GPIOB_PR, GPIO_PIN_1);//toggle bit 1 >>B1
			while((MCAL_GPIO_ReadPin(GPIOA_PR, GPIO_PIN_1) ==0));//Single press ..while am pressing>> same action
		}
		//Read Bit 13  ..PA13>>Connected External to PDR
		if(MCAL_GPIO_ReadPin(GPIOA_PR, GPIO_PIN_13) ==1)//Multi Pressing
		{
			MCAL_GPIO_TogglePin(GPIOB_PR, GPIO_PIN_13);//toggle bit 13 >>B13
			my_wait(1);

		}

	}

}
